"""
===============================================================
Module: Superstore logger- ETL Helper Functions

Purpose:
    This module contains various utility functions that support the Superstore ETL pipeline.
    These functions handle environment configuration, logging, and unique run ID generation.
    It is an essential part of the Superstore Medallion Architecture, providing necessary
    infrastructure to the pipeline for orchestrating, tracking, and logging the ETL process.

Key Features:
1. Environment Configuration:
    - Fetches environment-specific configurations to adjust the pipeline's behavior for different environments 
      (e.g., dev, qa, prod).
    - Includes functions for retrieving the pipeline name, version, and environment variables.
    - These values are used across the pipeline to ensure consistency in naming conventions and configuration.

2. Run ID Generation:
    - Provides a mechanism for generating unique run IDs to track the pipeline execution.
    - Generates a global `master_run_id` for the entire pipeline execution and a unique `layer_run_id` for each layer.
    - Run IDs are used for traceability, enabling proper tracking and debugging of pipeline runs.

3. Structured Logging:
    - Implements custom logging using a JSON formatter to log structured events, capturing critical metadata such as timestamps, 
      environment, pipeline version, run IDs, and layer information.
    - The log formatter also converts UTC timestamps to Australia/Sydney timezone to align with operational standards.
    - Provides a clear and consistent way to log structured events with key information to track pipeline progress and failures.
    - Logging levels supported: INFO, WARNING, ERROR, and DEBUG, ensuring detailed logging at every stage of the ETL process.

4. Metadata Enrichment:
    - The logging system supports enrichment of log events with metadata, such as pipeline execution context, environment details,
      and runtime configuration. This metadata is included in the log message for better traceability, and observability, 
      and helps debug issues.
    - Logs include optional attributes such as `master_run_id`, `layer_run_id`, `layer`, and custom metadata passed during logging.

5. Helper Functions for Orchestrator Integration:
    - Supports layer and master orchestrators by providing helper functions to generate unique run IDs (`create_run_id_for_layer` and `create_master_run_id`).
    - These run IDs allow for tracking each individual layer and the overall pipeline, enabling hierarchical orchestration.
    - Facilitates integration with the Superstore pipeline orchestrator, ensuring smooth flow across multiple pipeline layers.

6. Custom JSON Formatter:
    - Logs are formatted in a structured JSON format, making them easier to parse and analyze.
    - The formatter automatically handles time conversion from UTC to the `Australia/Sydney` timezone.
    - The JSON structure is designed to include all necessary metadata for monitoring, performance tracking, and debugging.

7. Metrics Collection & Observability:
    - Designed to support observability through structured logs that can be later analyzed for performance metrics.
    - Tracks critical pipeline events and logs detailed information for each pipeline run, including start/end times, layer run ID, and status.
    - Can be extended to integrate additional metrics related to pipeline execution (e.g., processing times, row counts, and errors).

8. Flexibility & Extensibility:
    - This module is designed to be flexible, allowing it to be easily integrated into various parts of the ETL pipeline.
    - Can be extended to accommodate additional pipeline metadata and enriched logging information.
    - Can be used across multiple layers and pipelines, ensuring consistency in pipeline execution tracking.

Best Practices:
    - Ensure that environment variables (such as `SUPERSTORE_ENV`, `SUPERSTORE_PIPELINE_NAME`, etc.) are correctly set for the pipeline to run successfully.
    - Utilize `get_superstore_logger` to create a logger for consistent structured logging throughout the pipeline.
    - Ensure each layer in the pipeline uses unique `layer_run_id` to provide granular insights into the pipeline execution.
    - Use the generated `master_run_id` to maintain global traceability of the entire pipeline run.
    - Regularly monitor log files generated by this module to track ETL progress, spot errors, and optimize performance.

Usage:
    - Import this module wherever logging, environment handling, or run ID generation is required.
    - Use the `get_superstore_logger` function to create a logger and use it for logging throughout the pipeline.
    - Utilize `create_master_run_id` and `create_run_id_for_layer` to generate unique identifiers for pipeline runs and layers.

===============================================================
"""

import logging
import json
import uuid
import pytz
from datetime import datetime
import os

import sys
sys.path.append('/Users/bireshmoktan@gmail.com/superstore_medallionarchitecture_dab/src/superstore_shared_utilities')
from superstore_platform_constants import BRONZE_LAYER, SILVER_LAYER, GOLD_LAYER, DEFAULT_PIPELINE_NAME, DEFAULT_PIPELINE_VERSION

# -----------------------------
# Helper functions to read runtime env
# -----------------------------
def get_env() -> str:
    """Return environment of the pipeline: dev, qa, prod"""
    return os.getenv("SUPERSTORE_ENV", "dev")  # fallback only if not set

def get_pipeline_name() -> str:
    """Return the pipeline name from environment variable"""
    return os.getenv("SUPERSTORE_PIPELINE_NAME", DEFAULT_PIPELINE_NAME)

def get_pipeline_version() -> str:
    """Return the pipeline version from environment variable"""
    return os.getenv("SUPERSTORE_PIPELINE_VERSION", DEFAULT_PIPELINE_VERSION)

# -----------------------------
# Generate Global Run IDs
# -----------------------------
def generate_run_id():
    """
    Generates a unique run ID for every pipeline run.
    """
    return str(uuid.uuid4())

# -----------------------------
# Custom JSON Formatter for Logs
# -----------------------------
class superstoreJsonFormatter(logging.Formatter):
    def format(self, record):
        """
        Converts the log record timestamp from UTC to Australia/Sydney timezone,
        formats the log as a structured JSON string, and includes metadata if present.
        """
        # Convert UTC timestamp from logging record to datetime
        utc_dt = datetime.utcfromtimestamp(record.created)
        # Set Sydney timezone
        sydney_tz = pytz.timezone("Australia/Sydney")
        # Convert UTC -> Sydney timezone
        sydney_dt = utc_dt.replace(tzinfo=pytz.utc).astimezone(sydney_tz)
        # ISO 8601 string with timezone offset
        timestamp_str = sydney_dt.isoformat()

        # Extract layer from metadata if present
        layer = getattr(record, "metadata", {}).get("layer")

        # Log record - Add both master_run_id and layer_run_id
        log_record = {
            "timestamp": timestamp_str,
            "env": get_env(),
            "pipeline": get_pipeline_name(),
            "pipeline_version": get_pipeline_version(),
            "master_run_id": getattr(record, "master_run_id", None),  # None if not passed
            "layer_run_id": getattr(record, "layer_run_id", None),    # None if not passed
            "layer": layer,
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage()
        }

        # Add remaining metadata (without overwriting 'layer')
        if hasattr(record, "metadata"):
            for k, v in record.metadata.items():
                if k != "layer":
                    log_record[k] = v

        # Include exception info if present
        if record.exc_info:
            log_record["exception"] = self.formatException(record.exc_info)

        return json.dumps(log_record)

# -----------------------------
# Logger Factory Function
# -----------------------------
def get_superstore_logger(name: str, level=logging.INFO) -> logging.Logger:
    """
    Returns a logger configured with superstoreJsonFormatter.
    Ensures only one StreamHandler is attached per logger.
    
    Args:
        name (str): Logger name, usually the module name.
        level (logging.LEVEL): Logging level (INFO, DEBUG, WARNING, etc.)
    """
    logger = logging.getLogger(name)
    logger.setLevel(level)
    if not logger.hasHandlers():
        handler = logging.StreamHandler()
        handler.setFormatter(superstoreJsonFormatter())
        logger.addHandler(handler)
    return logger

# -----------------------------
# Unified Logging Helper
# -----------------------------
def log_event(logger: logging.Logger, level: str, message: str, layer: str, master_run_id=None, layer_run_id=None, **kwargs):
    """
    Logs a structured JSON event with Sydney timestamp, master_run_id, layer_run_id, layer and optional metadata.
    
    Args:
        logger (logging.Logger): The logger instance.
        level (str): Log level: INFO, WARNING, ERROR, DEBUG.
        message (str): Main log message.
        master_run_id (str, optional): The global run ID for the entire pipeline.
        layer_run_id (str, optional): The run ID for the current pipeline layer.
        layer (str): The layer name for current pipeline run.
        **kwargs: Any extra metadata to include in the log (e.g., batch_id, source_path, rows).
    """
    # Include layer inside metadata if provided
    metadata = kwargs.copy()
    if layer:
        metadata["layer"] = layer

    # Add master_run_id and layer_run_id to metadata
    extra = {"metadata": metadata, "master_run_id": master_run_id, "layer_run_id": layer_run_id}
    level = level.upper()

    if level == "INFO":
        logger.info(message, extra=extra)
    elif level == "WARNING":
        logger.warning(message, extra=extra)
    elif level == "ERROR":
        logger.error(message, extra=extra)
    elif level == "DEBUG":
        logger.debug(message, extra=extra)
    else:
        logger.info(message, extra=extra)

# -----------------------------
# Helper for Layer-Orchestrator Integration
# -----------------------------
def create_run_id_for_layer():
    """
    Create a unique run ID for a specific layer. Each layer generates its own unique ID.
    """
    return generate_run_id()

# -----------------------------
# Helper for Master-Orchestrator Integration
# -----------------------------
def create_master_run_id():
    """
    Create a unique run ID for the entire pipeline (Master Orchestrator).
    """
    return generate_run_id()
