silver_table_configs:

  # -------------------------------
  # Customers table
  # -------------------------------
  - bronze_table: customers
    quarantine_table: customers_dirty
    silver_table: customers
    audit_table: customers_duplicates
    read_from_table: customers
    business_keys:
      - customer_id
    numeric_cast_cols: {}
    regex_cols: {}
    categorical_allowed_vals:
      region:
        - East
        - West
        - Central
        - South
    metrics_table: silver_layer_metrics
    layer_name: silver
    business_columns:
      - customer_id
      - customer_name
      - segment
      - country
      - state
      - city
      - postal_code
      - region
    meta_columns:
      - bronze_ingestion_ts
    ingestion_col: bronze_ingestion_ts

  # -------------------------------
  # Products table
  # -------------------------------
  - bronze_table: products
    quarantine_table: products_dirty
    silver_table: products
    audit_table: products_duplicates
    read_from_table: products
    business_keys:
      - product_id
    numeric_cast_cols: {}
    regex_cols: {}
    categorical_allowed_vals:
      category:
        - Furniture
        - Office Supplies
        - Technology
    metrics_table: silver_layer_metrics
    layer_name: silver
    business_columns:
      - product_id
      - product_name
      - category
      - sub_category
    meta_columns:
      - bronze_ingestion_ts
    ingestion_col: bronze_ingestion_ts


  # -------------------------------
  # Orders table
  # -------------------------------
  - bronze_table: orders
    quarantine_table: orders_dirty
    silver_table: orders
    audit_table: orders_duplicates
    read_from_table: orders
    business_keys:
      - order_id
    numeric_cast_cols: {}
    date_cast_cols:
      - order_date
      - ship_date
    regex_cols:
      # Replace / with [-/] to accept both hyphens and slashes as date separators.
      order_date: |
        (?ix)^(
          ([1-9]|0[1-9]|[12][0-9]|3[01])[-/]([1-9]|0[1-9]|1[0-2])[-/]\d{4} |
          \d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) |
          (0[1-9]|[12][0-9]|3[01])[-/](0[1-9]|1[0-2])[-/]\d{4} |
          \d{1,2}\s(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d{4} |
          \d{1,2}\s(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}
        )$
        ship_date: |
        (?ix)^(
          ([1-9]|0[1-9]|[12][0-9]|3[01])[-/]([1-9]|0[1-9]|1[0-2])[-/]\d{4} |
          \d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01]) |
          (0[1-9]|[12][0-9]|3[01])[-/](0[1-9]|1[0-2])[-/]\d{4} |
          \d{1,2}\s(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s\d{4} |
          \d{1,2}\s(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}
        )$

    categorical_allowed_vals: {}
    metrics_table: silver_layer_metrics
    layer_name: silver
    business_columns:
      - order_id
      - customer_id
      - order_date
      - ship_date
      - ship_mode
    meta_columns:
      - bronze_ingestion_ts
    ingestion_col: bronze_ingestion_ts


  # -------------------------------
  # Sales table
  # -------------------------------
  - bronze_table: sales
    quarantine_table: sales_dirty
    silver_table: sales
    audit_table: sales_duplicates
    read_from_table: sales
    business_keys:
      - order_id
      - product_id
    numeric_cast_cols:
      sales: decimal(10,2)
      profit: decimal(10,2)
      discount: decimal(10,2)
      quantity: int
    regex_cols:
      sales: '^\d+(\.\d+)?$'
      profit: '^-?\d+(\.\d+)?$'
      discount: '^\d+(\.\d+)?$'
      quantity: '^\d+$'
    categorical_allowed_vals: {}
    metrics_table: silver_layer_metrics
    layer_name: silver
    business_columns:
      - order_id
      - product_id
      - sales
      - quantity
      - discount
      - profit
    meta_columns:
      - bronze_ingestion_ts
    ingestion_col: bronze_ingestion_ts

