# =====================================================
# Superstore Gold Dimension Config 
# =====================================================
dim_config:
  customers:
    layer_name: Gold
    table_type: dimension
    dim_type: customers
    silver_tbl: customers             # Logical Silver table name
    gold_tbl: dim_customers           # Logical Gold table name
    metrics_table: gold_layer_metrics # Logical metrics table
    required_columns:
      - customer_id
      - customer_name
      - segment
      - country
      - state
      - city
      - postal_code
      - region
      # - silver_customers_hash_id
    natural_keys:
      - customer_id
    column_mapping:
      customer_name: customer_name
      segment: segment
      country: country
      state: state
      city: city
      postal_code: postal_code
      region: region
    hash_column: gold_customers_hash_id
    # silver_hash_column: silver_customers_hash_id
    z_order_cols:
      - region
      - state
    max_rows_per_bucket: 1000000

  products:
    layer_name: Gold
    table_type: dimension
    dim_type: products
    silver_tbl: products
    gold_tbl: dim_products
    metrics_table: gold_layer_metrics
    required_columns:
      - product_id
      - product_name
      - category
      - sub_category
      # - silver_products_hash_id
    natural_keys:
      - product_id
    column_mapping:
      product_id: product_id
      product_name: product_name
      category: category
      sub_category: sub_category
    hash_column: gold_products_hash_id
    # silver_hash_column: silver_products_hash_id
    z_order_cols:
      - category
      - sub_category
    max_rows_per_bucket: 1000000

